// GIFs
export const GET_GIFS_REQUEST = 'GET_GIFS_REQUEST';
export const GET_GIFS_SUCCESS = 'GET_GIFS_SUCCESS';
export const GET_GIFS_FAILURE = 'GET_GIFS_FAILURE';

// Favourites
export const GET_FAVOURITES_REQUEST = 'GET_FAVOURITES_REQUEST';
export const GET_FAVOURITES_SUCCESS = 'GET_FAVOURITES_SUCCESS';
export const GET_FAVOURITES_FAILURE = 'GET_FAVOURITES_FAILURE';
export const ADD_FAVOURITES_REQUEST = 'ADD_FAVOURITES_REQUEST';
export const ADD_FAVOURITES_SUCCESS = 'ADD_FAVOURITES_SUCCESS';
export const ADD_FAVOURITES_FAILURE = 'ADD_FAVOURITES_FAILURE';